// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Alert struct {
	ID      string `json:"id"`
	Message string `json:"message"`
	Area    *Area  `json:"area"`
}

type Area struct {
	Points []*Location `json:"points"`
}

type Location struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type LocationInput struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}
